services:
  adminer:
    image: adminer
    restart: always
    container_name: nested_sets_adminer
    ports:
      - 8086:8080 # runs at: localhost:8086

  postgres:
    image: postgres:15.8
    restart: always
    container_name: nested_sets_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432" # in adminer: host.docker.internal:5434
    volumes:
      - db:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    restart: always
    container_name: nested_sets_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: nested_sets_test
      MYSQL_USER: nested_sets
      MYSQL_PASSWORD: nested_sets
    ports:
      - "3307:3306" # in adminer: host.docker.internal:3307
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --wait_timeout=28800
      --interactive_timeout=28800
      --max_allowed_packet=256M
      --max_prepared_stmt_count=16382

volumes:
  db:
  mysql_data: